name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_GLOBAL_USER }}
          password: ${{ secrets.DOCKER_GLOBAL_PWD }}
          
      - name: Docker Build and Push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            fabricioveronez/sorteador:latest
            fabricioveronez/sorteador:v1
            kubedevio/sorteador:latest
            kubedevio/sorteador:v1
